image: Visual Studio 2017
environment:
  GOPATH: c:/gopath
  GOVERSION: 1.11
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    - CMAKE_GENERATOR: "Visual Studio 15 2017"
build_script:
  - cmd: go get -v github.com/bassosimone/mkbuild
  - cmd: "%GOPATH%/bin/mkbuild.exe autogen"
  - cmd: cmake -G "%CMAKE_GENERATOR%"
  - cmd: cmake --build -C Release .
  - cmd: ctest --output-on-failure -C Release -a
