language: go
go:
  - 1.11
services:
  - docker
sudo: required
matrix:
  include:
    - env: BUILD_TYPE="asan"
    - env: BUILD_TYPE="clang"
    - env: BUILD_TYPE="coverage"
    - env: BUILD_TYPE="ubsan"
    - env: BUILD_TYPE="vanilla"
script:
  - go get -v github.com/bassosimone/mkbuild
  - $GOPATH/bin/mkbuild docker $BUILD_TYPE
